### PR TITLE
Test validate tf

### PR DESCRIPTION
**Pull request by ralren**
## [Add the ability to commit and push changes made by terraform-fmt in the validate-tf GHA workflow](https://trello.com/c/s1jfNe0K)

Changes proposed in this pull request:

- what it says on the tin

### CODE REVIEW

**Comment by esacteksab** [comment]
I don't see any commits from a bot. I was sort of expecting to, should I not?

**Comment by ralren** [comment]
> I don't see any commits from a bot. I was sort of expecting to, should I not?

There's no bot used. It's a step after the pre-commit in GHA that detects if pre-commit failed. It then commits and pushes those changes. (See https://github.com/trussworks/terraform-aws-bootstrap/pull/109/commits/7cd7960327c69014433b5278d02cf7c15956f7c3) Then a new workflow is triggered which is what happens here https://github.com/trussworks/terraform-aws-bootstrap/pull/109/commits/13aa53beea71823fa098f6a47085882eecc279ae

**Comment by esacteksab** [comment]
I missed this https://github.com/trussworks/terraform-aws-bootstrap/pull/109/commits/13aa53beea71823fa098f6a47085882eecc279ae 

`ralren authored and github-actions bot committed Jun 1, 2023`

**Review by esacteksab — APPROVED** [review]
Thank you for this!

**Pull request closed without merging**
